# Generated by Django 5.1 on 2024-08-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_workoutexercise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
    ]
